version: "3.1"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - data:/var/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  data: